version: '3.3'

services:
  marytts:
    image: korerorero-marytts:latest
    container_name: korerorero-marytts
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-marytts.git
    volumes:
      - ./build:/build     
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.proxy
    networks:
      - default
    links:
      - marytts
    ports:
      - "3000:3000"

