version: '3.3'
services:
  tts:
    image: korerorero-tts:latest
    container_name: korerorero-tts
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-marytts.git
    volumes:
      - ./build:/build
    networks:
      - default        
  orchestration:
    image: korerorero-orchestration:latest
    container_name: korerorero-orchestration
    env_file:
      - orchestration.env
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-orchestration.git
    volumes:
      - ./build:/build
    networks:
      - default        
  mouth-shapes:
    image: korerorero-mouth-shapes:latest
    container_name: korerorero-mouth-shapes
    env_file:
      - mouth-shapes.env
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-mouth-shapes.git
    volumes:
      - ./build:/build               
    networks:
      - default  
    links:
      - tts      
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.proxy
    networks:
      - default
    links:
      - tts
      - orchestration
      - mouth-shapes
    ports:
      - "8000:8000"

