version: '3.3'
services:
  front-end:
    image: korerorero-front-end:latest
    container_name: korerorero-front-end
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-front-end.git#v0.1.1
    volumes:
      - ./build:/build
    networks:
      - default
  tts:
    image: korerorero-tts:latest
    container_name: korerorero-tts
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-marytts.git#v1.0.1
    volumes:
      - ./build:/build
    networks:
      - default        
  orchestration:
    image: korerorero-orchestration:latest
    container_name: korerorero-orchestration
    env_file:
      - orchestration.env
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-orchestration.git#v0.1.0
    volumes:
      - ./build:/build
    networks:
      - default      
    links:
      - tts
      - mouth-shapes
  mouth-shapes:
    image: korerorero-mouth-shapes:latest
    container_name: korerorero-mouth-shapes
    env_file:
      - mouth-shapes.env
    build:
     context: https://github.com/ServiceInnovationLab/korerorero-mouth-shapes.git#v0.1.0
    volumes:
      - ./build:/build               
    networks:
      - default  
    links:
      - tts      
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.proxy
    networks:
      - default
    links:
      - front-end
      - orchestration
    ports:
      - "8000:8000"

