version: '2'
services:
  web-a:
    build:
      context: ./
      dockerfile: Dockerfile.web
    networks:
      - default
  web-b:
    build:
      context: ./
      dockerfile: Dockerfile.web
    networks:
      - default
  web-c:
    build:
      context: ./
      dockerfile: Dockerfile.web
    networks:
      - default
  mothership:
    build:
      context: ./
      dockerfile: Dockerfile.mothership
    networks:
      - default
    depends_on:
      - web-a
      - web-b
      - web-c
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.proxy
    networks:
      - default
    links:
      - mothership
      - web-a
      - web-b
      - web-c
    ports:
      - "3000:3000"
