version: '3.6'
services:
  front-end:
    image: korerorero-front-end:latest
    container_name: korerorero-front-end
    build:
      context: /Users/conrad/dev/korerorero/korerorero-front-end
    volumes:
      - ./build:/build
    networks:
      - default
  tts:
    image: korerorero-tts:latest
    container_name: korerorero-tts
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-marytts.git
    volumes:
      - ./build:/build
    networks:
      - default        
  orchestration:
    image: korerorero-orchestration:latest
    container_name: korerorero-orchestration
    env_file:
      - orchestration.env
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-orchestration.git#implement-receive-message-api
    volumes:
      - ./build:/build
    networks:
      - default      
    links:
      - tts          
  mouth-shapes:
    image: korerorero-mouth-shapes:latest
    container_name: korerorero-mouth-shapes
    env_file:
      - mouth-shapes.env
    build:
     context: https://github.com/ServiceInnovationLab/korerorero-mouth-shapes.git#install-chat-ui
     volumes:
      - ./build:/build               
    networks:
      - default  
    links:
      - tts      
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.proxy
    networks:
      - default
    links:
      - front-end
      - tts
      - orchestration
      - mouth-shapes
    ports:
      - "8000:8000"

