version: '3.3'
services:
  mouth-shapes:
    image: korerorero-mouth-shapes:latest
    container_name: korerorero-mouth-shapes
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-mouth-shapes.git
    volumes:
      - ./build:/build     
  tts:
    image: korerorero-marytts:latest
    container_name: korerorero-marytts
    build:
      context: https://github.com/ServiceInnovationLab/korerorero-marytts.git
    volumes:
      - ./build:/build     
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.proxy
    networks:
      - default
    links:
      - tts
      - mouth-shapes
    ports:
      - "3000:3000"

